import { createClient } from "@supabase/supabase-js";
import { runSafeAutofillForItem, undoAutofill, saveAutofillSettings, loadAutofillSettings } from "@/lib/safe-autofill.server";
import { normalizeBodyType } from "@/lib/safe-autofill";
const sb = createClient(process.env.SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { persistSession: false } });
const { data: v } = await sb.from("vehicles").select("id").eq("unit_number", "TEST-AF-1").single();
const { data: items } = await sb.from("fleet_import_items").select("id,doc_class").in("file_name", ["TEST-af-registration.pdf", "TEST-af-insurance.pdf"]);
const reg = items!.find((i) => i.doc_class === "registration")!.id, ins = items!.find((i) => i.doc_class === "insurance_card")!.id;
const veh = async () => (await sb.from("vehicles").select("trim,body_type,color,seats,fuel_type,license_plate,current_odometer").eq("id", v!.id).single()).data;
console.log("default settings", await loadAutofillSettings(sb));
console.log("1 OFF run", await runSafeAutofillForItem(sb, reg), await veh());
await saveAutofillSettings(sb, { enabled: true, daily_cap: 1 });
console.log("2 cap=1 run", await runSafeAutofillForItem(sb, reg), await veh());
await saveAutofillSettings(sb, { enabled: true, daily_cap: 50 });
console.log("3 cap=50 run", await runSafeAutofillForItem(sb, reg), await veh());
console.log("4 insurance source run", await runSafeAutofillForItem(sb, ins), await veh());
console.log("5 rerun (idempotent)", await runSafeAutofillForItem(sb, reg));
const { data: ev } = await sb.from("vehicle_autofill_events").select("field,previous_value,new_value,page,doc_class,evidence_raw,confidence,actor,document_id,created_at").eq("vehicle_id", v!.id);
console.log("events", ev);
console.log("provenance", (await sb.from("vehicle_field_provenance").select("field,value,method,document_id").eq("vehicle_id", v!.id)).data);
console.log("odometer readings", (await sb.from("odometer_readings").select("id").eq("vehicle_id", v!.id)).data?.length);
console.log("expenses", (await sb.from("vehicle_expenses").select("id").eq("vehicle_id", v!.id)).data?.length);
// manual edit after autofill: trim changed by a person
await sb.from("vehicles").update({ trim: "Titanium" }).eq("id", v!.id);
await sb.from("audit_log").insert({ action: "vehicle.identity.updated", summary: "TEST manual edit", entity_type: "vehicle", entity_id: v!.id, metadata: { trim: { from: "SE", to: "Titanium" } } });
const owner = (await sb.from("user_roles").select("user_id").eq("role", "admin").limit(1).single()).data!.user_id;
console.log("6 undo vehicle", await undoAutofill(sb, { userId: owner }, { vehicleId: v!.id }), await veh());
console.log("undo results", (await sb.from("vehicle_autofill_events").select("field,undo_result").eq("vehicle_id", v!.id)).data);
// error -> pause
await saveAutofillSettings(sb, { enabled: true, daily_cap: 50 });
console.log("7 bad item", await runSafeAutofillForItem(sb, "00000000-0000-0000-0000-000000000000"));
console.log("bodytype map", normalizeBodyType("4D","Fusion"), normalizeBodyType("4D","Escape"), normalizeBodyType("UT","Explorer"), normalizeBodyType("4DR","Camry"));
await sb.from("app_settings").delete().eq("key", "safe_autofill");
console.log("final settings", await loadAutofillSettings(sb));
