/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as InvestorFaqRouteImport } from './routes/investor-faq'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FleetIdRouteImport } from './routes/fleet.$id'
import { Route as ApplyStep2RouteImport } from './routes/apply.step2'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorFaqRoute = InvestorFaqRouteImport.update({
  id: '/investor-faq',
  path: '/investor-faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetIdRoute = FleetIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FleetRoute,
} as any)
const ApplyStep2Route = ApplyStep2RouteImport.update({
  id: '/step2',
  path: '/step2',
  getParentRoute: () => ApplyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/fleet': typeof FleetRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/investor-faq': typeof InvestorFaqRoute
  '/investors': typeof InvestorsRoute
  '/partner': typeof PartnerRoute
  '/partners': typeof PartnersRoute
  '/portal': typeof PortalRoute
  '/apply/step2': typeof ApplyStep2Route
  '/fleet/$id': typeof FleetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/fleet': typeof FleetRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/investor-faq': typeof InvestorFaqRoute
  '/investors': typeof InvestorsRoute
  '/partner': typeof PartnerRoute
  '/partners': typeof PartnersRoute
  '/portal': typeof PortalRoute
  '/apply/step2': typeof ApplyStep2Route
  '/fleet/$id': typeof FleetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/fleet': typeof FleetRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/investor-faq': typeof InvestorFaqRoute
  '/investors': typeof InvestorsRoute
  '/partner': typeof PartnerRoute
  '/partners': typeof PartnersRoute
  '/portal': typeof PortalRoute
  '/apply/step2': typeof ApplyStep2Route
  '/fleet/$id': typeof FleetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/contact'
    | '/faq'
    | '/fleet'
    | '/how-it-works'
    | '/investor-faq'
    | '/investors'
    | '/partner'
    | '/partners'
    | '/portal'
    | '/apply/step2'
    | '/fleet/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apply'
    | '/contact'
    | '/faq'
    | '/fleet'
    | '/how-it-works'
    | '/investor-faq'
    | '/investors'
    | '/partner'
    | '/partners'
    | '/portal'
    | '/apply/step2'
    | '/fleet/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply'
    | '/contact'
    | '/faq'
    | '/fleet'
    | '/how-it-works'
    | '/investor-faq'
    | '/investors'
    | '/partner'
    | '/partners'
    | '/portal'
    | '/apply/step2'
    | '/fleet/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApplyRoute: typeof ApplyRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FleetRoute: typeof FleetRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  InvestorFaqRoute: typeof InvestorFaqRoute
  InvestorsRoute: typeof InvestorsRoute
  PartnerRoute: typeof PartnerRoute
  PartnersRoute: typeof PartnersRoute
  PortalRoute: typeof PortalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor-faq': {
      id: '/investor-faq'
      path: '/investor-faq'
      fullPath: '/investor-faq'
      preLoaderRoute: typeof InvestorFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/$id': {
      id: '/fleet/$id'
      path: '/$id'
      fullPath: '/fleet/$id'
      preLoaderRoute: typeof FleetIdRouteImport
      parentRoute: typeof FleetRoute
    }
    '/apply/step2': {
      id: '/apply/step2'
      path: '/step2'
      fullPath: '/apply/step2'
      preLoaderRoute: typeof ApplyStep2RouteImport
      parentRoute: typeof ApplyRoute
    }
  }
}

interface ApplyRouteChildren {
  ApplyStep2Route: typeof ApplyStep2Route
}

const ApplyRouteChildren: ApplyRouteChildren = {
  ApplyStep2Route: ApplyStep2Route,
}

const ApplyRouteWithChildren = ApplyRoute._addFileChildren(ApplyRouteChildren)

interface FleetRouteChildren {
  FleetIdRoute: typeof FleetIdRoute
}

const FleetRouteChildren: FleetRouteChildren = {
  FleetIdRoute: FleetIdRoute,
}

const FleetRouteWithChildren = FleetRoute._addFileChildren(FleetRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApplyRoute: ApplyRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FleetRoute: FleetRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  InvestorFaqRoute: InvestorFaqRoute,
  InvestorsRoute: InvestorsRoute,
  PartnerRoute: PartnerRoute,
  PartnersRoute: PartnersRoute,
  PortalRoute: PortalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
